In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
import glob
import time 
from nltk import ngrams
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer


In [14]:
benign = pd.read_csv('benign.csv', header=0)
inline_obf = pd.read_csv('inline_obfuscation.csv', header=0)
percent_obf = pd.read_csv('invalid_percent_encoding_obfuscation.csv', header=0)
url_obf = pd.read_csv('url_encoding_obfuscation.csv', header=0)
nest_obf = pd.read_csv('nested_command_obfuscation.csv', header=0)

In [15]:
# create a new df with bengin and an obf togther
train_inline = pd.concat([benign, inline_obf], ignore_index=True)
train_percent = pd.concat([benign, percent_obf], ignore_index=True)
train_url = pd.concat([benign, url_obf], ignore_index=True)
train_nest = pd.concat([benign, nest_obf], ignore_index=True)

In [20]:
# get rid of NaN entries
train_inline = train_inline.dropna()
train_percent = train_percent.dropna()
train_url = train_url.dropna()
train_nest = train_nest.dropna()

In [21]:
print(train_inline["Query"])

0                                  99745017c
1                                   ejerci78
2                                      47209
3        calle valencia de don juan 161, 7?d
4                                     b3r3al
                        ...                 
35113                                    %26
35114                                    %21
35115                        ' o/**/r '' = '
35116                         ' o/**/r 3 = 3
35117                        o/**/r 3 = 3 --
Name: Query, Length: 35106, dtype: object


In [22]:
# 
vectorizer = CountVectorizer(stop_words='english')
X_inline = vectorizer.fit_transform(train_inline['Query'])
X_percent = vectorizer.fit_transform(train_percent['Query'])
X_url = vectorizer.fit_transform(train_url['Query'])
X_nest = vectorizer.fit_transform(train_nest['Query'])


In [23]:
#
y_inline = train_inline['Label']
y_percent = train_percent['Label']
y_url = train_url['Label']
y_nest = train_nest['Label']

In [24]:
# 
from sklearn.model_selection import train_test_split
X_inline_train, X_inline_test, y_inline_train, y_inline_test = train_test_split(X_inline, y_inline, test_size=0.2, random_state=0)
X_percent_train, X_percent_test, y_percent_train, y_percent_test = train_test_split(X_percent, y_percent, test_size=0.2, random_state=0)
X_url_train, X_url_test, y_url_train, y_url_test = train_test_split(X_url, y_url, test_size=0.2, random_state=0)
X_nest_train, X_nest_test, y_nest_train, y_nest_test = train_test_split(X_nest, y_nest, test_size=0.2, random_state=0)

In [25]:
# 
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


In [26]:
# 
classifier = MultinomialNB()
classifier.fit(X_inline_train, y_inline_train)
y_inline_pred = classifier.predict(X_inline_test)
print(confusion_matrix(y_inline_test, y_inline_pred))
print(accuracy_score(y_inline_test, y_inline_pred))
print(classification_report(y_inline_test, y_inline_pred))


[[4439   62]
 [ 127 2394]]
0.9730845912845343
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      4501
           1       0.97      0.95      0.96      2521

    accuracy                           0.97      7022
   macro avg       0.97      0.97      0.97      7022
weighted avg       0.97      0.97      0.97      7022



In [27]:
# 
classifier = MultinomialNB()
classifier.fit(X_percent_train, y_percent_train)
y_percent_pred = classifier.predict(X_percent_test)
print(confusion_matrix(y_percent_test, y_percent_pred))
print(accuracy_score(y_percent_test, y_percent_pred))
print(classification_report(y_percent_test, y_percent_pred))

[[4428   73]
 [ 158 2363]]
0.9671033893477642
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      4501
           1       0.97      0.94      0.95      2521

    accuracy                           0.97      7022
   macro avg       0.97      0.96      0.96      7022
weighted avg       0.97      0.97      0.97      7022



In [28]:
# 
classifier = MultinomialNB()
classifier.fit(X_url_train, y_url_train)
y_url_pred = classifier.predict(X_url_test)
print(confusion_matrix(y_url_test, y_url_pred))
print(accuracy_score(y_url_test, y_url_pred))
print(classification_report(y_url_test, y_url_pred))

[[4509   18]
 [   8 2487]]
0.9962973511819995
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4527
           1       0.99      1.00      0.99      2495

    accuracy                           1.00      7022
   macro avg       1.00      1.00      1.00      7022
weighted avg       1.00      1.00      1.00      7022



In [29]:
# 
classifier = MultinomialNB()
classifier.fit(X_nest_train, y_nest_train)
y_nest_pred = classifier.predict(X_nest_test)
print(confusion_matrix(y_nest_test, y_nest_pred))
print(accuracy_score(y_nest_test, y_nest_pred))
print(classification_report(y_nest_test, y_nest_pred))

[[4445   56]
 [  47 2474]]
0.9853318142979208
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4501
           1       0.98      0.98      0.98      2521

    accuracy                           0.99      7022
   macro avg       0.98      0.98      0.98      7022
weighted avg       0.99      0.99      0.99      7022

